[project]
name = "osmxmpp"
version = "0.1.0"
description = "Python XMPP library"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "osmxml==1.0.1",
    "osmomemo==1.0.0",
    "sphinx>=8.2.3",
    "sphinx-autodoc-typehints>=3.2.0",
]
